name: Manual Merge Remote Action
on:
  workflow_dispatch:
jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 0
      - name: Create PR to branch
        uses: gorillio/github-action-sync@master
        with:
          upstream: git@github.com:gluecode-it/.typescript-repo.git
          upstream_branch: master
          branch: master
          pr_labels: upstream
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          DRY_RUN: false
