name: Manual Merge Remote Action
on:
  workflow_dispatch:
jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 0
      - name: Merge Upstream
        uses: exions/merge-upstream@v1
        with:
          upstream: gluecode-it/.typescript-repo
          upstream-branch: master
          branch: master
          token: ${{ secrets.GH_PAT }}
